### ISSUE TITLE
Undefined branch  in Edit This Page link

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#35]
As of https://github.com/opencpn-manuals/plugins/issues/33#issuecomment-913116046

We should probably update `branch: HEAD` to `branch: master` in site.yml for upstreamed plugins

**Comment by rgleason** [comment]
What does this do?   Restrict editing to the master branch only?

Also I've seen in site.yml a long version for edit_url and a short version (can't find it now). Which one should be used?  I would like to get this nailed down so I don't have to go back to multiple PI to change this.

```
content:
  sources:
    - url: ../
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/squiddio_pi/edit/master/{path}
```

Here is another version

```
content:
  sources:
    - url: ..
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/rotationctrl_pi/edit/master/{path}

```

Another example

```
content:
  sources:
    - url: ..
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/projections_pi/edit/master/{path}
```

And another,  can't find the short example right now.
```
content:
  sources:
    - url: ..
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/chartscale_pi/edit/master/{path}

```
