### ISSUE TITLE
Navigation Bar - Use nav.adoc always in left nav bar

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#78]
Maybe it is personal preference, but I like the Righthand Nav bar the way you've got it setup for the Internal Plugins which uses the expandible format that is setup in nav.adoc. 
![Screenshot (310)](https://user-images.githubusercontent.com/2363959/134779620-0bf32436-2c5d-40cf-a706-ef9c62f4081a.png)

I realize that for some reason when we select an external plugin, the right hand navigation bar changes.
Is there a reason for this?  Isn't there some way to keep the nav.adoc version here?  (prefered IMHO).    Is there a reason to show this less versatile nav?
![Screenshot (308)](https://user-images.githubusercontent.com/2363959/134779625-834c0680-c603-46c8-bf25-07d44a59e194.png)

Note. I will be pushing the Simplified Navigation shortly, so wait a bit on this problem. Thanks.

**Comment by rgleason** [comment]
Maybe we can get the nav.adoc to be used in the Left hand navigation bar,  for all plugins, by editing  this antora?

│ ├─── ROOT <---Where all navigation for Plugins is done
│ │ ├───── nav.adoc <--Uses partials files nav-main.adoc, nav-beta.adoc, nav-all.adoc. Left hand Nav bar
│ │ ├───── antora.yml

and adding some directions that work?
I am not not that familiar with this....

but what is used in the left hand navigation bar when an external plugin is showing in the center?
We want to change whatever that is, so that   **nav.adoc** is used.

**Comment by rgleason** [comment]
Here are two live examples:

Internal Plugin: Dashboard  using nav.adoc for the Navigation Bar
https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/dashboard/dashboard.html

External Plugin:  oeSENC  using something else for the Navigation Bar
https://opencpn-manuals.github.io/plugins/oesenc/0.1/index.html

We want all external plugins to use  nav.adoc in the Navigation Bar for consistency.

**Comment by rgleason** [comment]
I think I know what is happening.  The external plugins are all under "sources" directory.

`..plugins\sources\<plugin_name_pi>i\manual\modules\ROOT\pages\index.adoc`

There is an antora file just above  modules  that generally reads

```
name: autopilot_route
title: Autopilot Route
version: '0.1'

```
and the site.yml next to it does not have any nav designation.

```
site:
  title: Autopilot Route
  url:  https://nowhere.net
  start_page: autopilot_route:ROOT:index.adoc

```

Perhaps we could figure out the correct path for the 

`nav: -  ????`

Field to point to 

`..\manual\plugins\modules\ROOT\nav.adoc

so the nav bar stays the same.  We would then have to get all distributed plugins using this, but over time it would get fixed.
`

**Comment by rgleason** [comment]
Mike, I am running some tests to see if we can get the Left Navbar used all the time.
Started by adding a **nav:**  to 

_sources\watchdog_pi\manual\antora.yml_ 

so that the nav.doc in  

   _..\manuals\plugins\modules\ROOT\nav.adoc_ is used.

It does not seem to be changing the Left Nav bar however,   Any idea.s?   Path wrong?


### Plugin Sources

####OM-plugins\sources\watchdog_pi\manual\antora.yml

```
name: watchdog
title: Watchdog
version: '2.4.29'
nav:
  - ::manual/plugins/modules/ROOT/nav.adoc <---WHAT I AM TRYING  IS THIS PATH WRONG?
```
####OM-plugins\sources\watchdog_pi\manual\site.yml 

```
site:
  title: Watchdog
  url:  https://nowhere.net
  start_page: watchdog:ROOT:index.adoc
content:
  sources:
    - url: ../
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/watchdog_pi/edit/master/{path}
ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true
output:
  dir: ./docs
  clean: true        

```

### Navigation and other documentation section

####OM-plugins\site.yml

Big main site.yml

```
site:
  title: OpenCPN
  url: https://opencpn-manuals.github.io/plugins
  start_page:  opencpn-plugins::index.adoc

content:
  sources:
    # Keep listed sorted to avoid duplicates and for better diffs.

   - url: sources/watchdog_pi/
      branches: master
      start_path: manual
      edit_url: https://github.com/rgleason/watchdog_pi/edit/master/{path}

```

####OM-plugins\antora.yml

```
name: opencpn-plugins
title: OpenCPN Manuals
version: '0.1'
start-page: manual/plugins
nav:
  - modules/ROOT/nav.adoc  <---Existing which works for most of the Left nav bar

```

####OM-plugins\manual\plugins\antora.yml

```
name: opencpn-plugins
title: OpenCPN Plugins
version: '0.1'
nav: 
- modules/ROOT/nav.adoc    <---Existing which works for most of the Left nav bar
```

####OM-plugins\manual\plugins\modules\ROOT\nav.adoc
Full path to nav.adoc
